AutoEscola/Areas/Admin/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoEscola.Models;
using AutoEscola.Models.Repositorios;
using AutoEscola.Models.Servicos.Interfaces;
using AutoEscola.Controllers;

namespace AutoEscola.Areas.Admin.Controllers
{
    public class UsuarioController : Controller
    {
        private IServicosUsuarioAdmin ServicosUsuarioAdmin;

        public UsuarioController(IServicosUsuarioAdmin servicoUsuario)
        {
            this.ServicosUsuarioAdmin = servicoUsuario;
        }

        public ActionResult Create()
        {
            var usuario = new Usuario();
            usuario.Pessoa = new Pessoa();
            usuario.Pessoa.Empresa = new Empresa();
            return View(usuario);
        }

        [HttpPost]
        [HandleError]
        public ActionResult Create(Usuario usuario)
        {
            ServicosUsuarioAdmin.CriarContaDeUsuarioSuperAdminFree(usuario);

            if (ServicosUsuarioAdmin.ExisteErros())
            {
                foreach (string mensagem in ServicosUsuarioAdmin.Erros())
                    ModelState.AddModelError("", mensagem);
                return View(usuario);
            }

            EnviarEmail(usuario);

            return RedirectToAction("Confirmar", "Conta", new { area = "" });
        }

        private void EnviarEmail(Usuario usuario)
        {
            var email = new EmailController();
            email.VerificationEmail(usuario).Deliver();
        }

        [HttpPost]
        [HandleError]
        public ActionResult logar(FormCollection formulario)
        {
            var usuario = formulario["usuario"];
            var senha = formulario["senha"];

            if (ServicosUsuarioAdmin.Logar(usuario, senha))
                return RedirectToAction("HomeAdmin", "Index");
            if (ServicosUsuarioAdmin.LogarFreeTour(usuario, senha))
                return RedirectToAction("HomeAdmin", "Index");
            else
                return RedirectToAction("ErroLogin");
        }

        public ActionResult ErroLogin()
        {
            ViewBag.Login = "admin";
            foreach (string mensagem in ServicosUsuarioAdmin.Erros())
                ModelState.AddModelError("", mensagem);
            return View();
        }

        [HttpGet]
        public ActionResult Desconectar()
        {
            ServicosUsuarioAdmin.Desconectar();
            return RedirectToAction("Index", "Home");
        }

    }
}

AutoEscola/Areas/Alunos/Controllers/HomeAlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoEscola.Areas.Alunos.Controllers
{
    public class HomeAlunosController : Controller
    {
        //
        // GET: /Alunos/HomeAlunos/

        public ActionResult Index()
        {
            return View();
        }

    }
}

AutoEscola/Views/Shared/DefaultScripts.cshtml
@{
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}

AutoEscola/Views/Shared/_Autenticacao.cshtml
<div id="autenticacao">
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Desconectar", "Desconectar", "Usuario", new { area = "" }, null) 
    }
    @if (!HttpContext.Current.User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Conectar", "Conectar", "Usuario")
    }
</div>

AutoEscola/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/info-box.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/page-header.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/botoes.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/formulario.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/menu.css")" rel="stylesheet" type="text/css" />
    @RenderSection("css", required: false)

    @RenderSection("analytics", required: false) 
</head>
<body>
    @RenderBody()
    @RenderPage("DefaultScripts.cshtml")
    @RenderSection("scripts", required: false)
</body>
</html>

AutoEscola/Views/Shared/_Login.cshtml
@using (Html.BeginForm("logar", "Usuario", FormMethod.Post, null))
{
    @Html.ValidationSummary(true, "Erro ao tentar logar")
    <h2>Login</h2>
    <div>
        <label class="form_label">
            Usuário ( informe login ou email )</label>
        <div class="form_edit_text">
            @Html.Editor("usuario")
        </div>
        <label class="form_label">
            Senha</label>
        <div class="form_edit_text">
            @Html.Password("senha")
        </div>

        @{
            if (ViewBag.Login == "aluno")
            {
                <input class="button blue" type="submit" value="Acessar" />
                <span>Ou</span>
                @Html.ActionLink("Criar conta agora", "Create", "Usuario", null, new { @class = "button blue" })
            }

            if (ViewBag.Login == "admin")
            {
                <input class="button green" type="submit" value="Acessar" />
                <span>Ou</span>
                @Html.ActionLink("Criar conta agora", "Create", "Usuario", null, new { @class = "button green" })
            }
        }
    </div>
}

AutoEscola/Views/Shared/_Menu.cshtml
<div class="menu">
    <div class="inner-menu">
        <ul>
            <li>
                @{
                    if (ViewBag.Login == "index")
                    {
                        @Html.ActionLink("Página Inicial", "Index", "Home", new { area = "" }, new { @class = "button orange" }) 
                    }
                    else
                    {
                        @Html.ActionLink("Página Inicial", "Index", "Home", new { area = "" }, new { @class = "button gray" }) 
                    }
                }
            </li>
            <li>
                @{
                    if (ViewBag.Login == "aluno")
                    {
                        @Html.ActionLink("Área do aluno", "Index", "HomeAlunos", new { area = "Alunos" }, new { @class = "button blue" })
                    }
                    else
                    { 
                        @Html.ActionLink("Área do aluno", "Index", "HomeAlunos", new { area = "Alunos" }, new { @class = "button gray" })
                    }
                }
            </li>
            <li>
                @{
                    if (ViewBag.Login == "admin")
                    {
                        @Html.ActionLink("Área do gestor", "Index", "HomeAdmin", new { area = "Admin" }, new { @class = "button green" })
                    }
                    else
                    {
                        @Html.ActionLink("Área do gestor", "Index", "HomeAdmin", new { area = "Admin" }, new { @class = "button gray" })
                    }
                    }
            </li>
        </ul>
    </div>
</div>